name: Update Base Branch

on:
  pull_request_target:
    types: [ labeled ]

jobs:
  update:
    if: ${{ github.event.label.name == 'update-base' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/update-base/
        id: update-base
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: ${{ github.event.number }}
      - name: Drop invalid mappings
        if: ${{ steps.update-base.outputs.result == 'success' }}
        run: ./gradlew dropInvalidMappings --stacktrace
      - name: Commit changes
        if: ${{ steps.update-base.outputs.result == 'success' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add mappings/
          git commit -m "Drop invalid mappings"
          git push
